require:
  - rubocop-minitest

AllCops:
  NewCops: disable
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/LineLength:
  Max: 125
  AutoCorrect: true

Lint/SuppressedException:
  Exclude:
    - "test/**/*"

# Because we use NotImplementErrors, we should
# not care about this in exercises
Lint/UnusedMethodArgument:
  Exclude:
    - "exercises/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  # We probably want to bring this down but let's start here for now
  Max: 20
  Exclude:
    - "test/**/*"

Naming/PredicateName:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

# I don't mind this being enabled if
# someone fixes all the fails.
Style/ClassAndModuleChildren:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/LambdaCall:
  EnforcedStyle: braces

Style/BlockComments:
  Enabled: false
