# For more information about this file, see
# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
# for detailed configuration information.

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: disable
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: only_before

Layout/LineLength:
  Max: 125
  AutoCorrect: true

Lint/SuppressedException:
  Exclude:
    - "test/**/*"

# Because we use NotImplementErrors, we should
# not care about this in exercises
Lint/UnusedMethodArgument:
  Exclude:
    - "exercises/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  # We probably want to bring this down but let's start here for now
  Max: 20
  Exclude:
    - "test/**/*"

Naming/PredicateName:
  Enabled: true
  Exclude:
    - "exercises/concept/amusement-park-improvements/attendee.rb"

Style/ConditionalAssignment:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: normalcase

Style/LambdaCall:
  EnforcedStyle: braces

Style/BlockComments:
  Enabled: false

# We use Heredoc indentation in exercises
# where variable indentation is desirable
Layout/HeredocIndentation:
  Enabled: true

Style/AsciiComments:
  Enabled: true
  Exclude:
    - "exercises/concept/moviegoer/moviegoer.rb"
