name: Exercise tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
        ruby-version: [3.2, 3.3]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Lint
        run: bundle exec rubocop -fs --except Metrics --config .rubocop.yml

      - name: Test exercises
        run: bundle exec rake test
